### ISSUE TITLE
Energenie ENER314-RT

### ISSUE THREAD

**Issue by DrConradInTheHouse** [davet2001/miscellaneous#1]
Hi, I have tried this with my Energenie ENER314-RT but not got it working. Must be a config/setup. It works with gpbenton's mqttclient ...
https://github.com/gpbenton/engMQTTClient/pull/19#issuecomment-685341216 
... that you dropped in favour of this much cleaner setup. Any ideas how I get this working ?

I installed rpi-rf using pip3 and then what? I do not know what the home code is or channel. 
 I do not have a remote but rather used that engMQTTclient software where I just held the button (on the plug socket) in for 5 seconds, it flashed, I sent a "On" to 8008 (hex code for the socket as reported by engMQTTclient) and it paired then worked.

Your way is much better, Are you able to help please?

- Daz

**Comment by davet2001** [comment]
Hi, I'm not sure whether you are trying to do what I did, but I'll try to help anyway!

I assume you are referring to https://github.com/davet2001/miscellaneous/blob/master/energenie_rpi-rf_433.sh?

I have an ENER314-RT but I don't use it any more.  Instead I use the most basic 433 MHz transmitter (3 pin device), like those available from aliexpress.

I don't know if there's a way to use the ENER314-RT in place of the simple 3pin 433MHz transmitter with my script.
`rpi-rf` (https://github.com/milaq/rpi-rf)
provides the `rpi-rf_send` command, but it needs you to tell it which RPi pin your transmitter is on.

If you want to use the hand remote, you need to learn the house code.  It can be done two ways:
1) with a USB DVB type SDR device to listen to and decode the house remote using universal radio hacker, then working out the symbol timing and pattern manually.
2) via a brute force method such as this script https://github.com/whaleygeek/pyenergenie/issues/81#issuecomment-313512879

Both ways need patience though!

If you aren't bothered about using the hand remote at all, you don't need to learn it's code.  You could just pick any house code such as the one on my example, and teach your socket to respond to it (after that your remote won't do anything).

**Comment by DrConradInTheHouse** [comment]
Yes, that's the script.
But how do i find which GPIO the 314RT hat is on. i tried all with the rpi-rf command but couldn't get the sockets to do anything. Don't even know if it's working. 

works fine with that engMQTTclient but that's a huge overkill, same reason like you i want to ditch it

EDIT: 
Dave, I do not have a remote. Never have. 
Just use the 315RT board with gpbenton's engMQTTclient.
I also have MiHome TRVs on the same 433RF network and also controlled using engMQTTclient.
I do not know how to use the home assistant 433RF integrations with these. 
As a start I thought I'd use your script - but doesnt do anything , clearly my setup , and need help.

I used every GPIO in the attached pic, substituting GPIO-NUMBER-HERE
Using the command: 
` housecode=0xfd160; channel=3; newstate=1; rpi-rf_send -g <<GPIO-NUMBER-HERE>>   $(($housecode*16+16#$(echo $((channel)) | tr '12345678' 'e6a2c480')+$newstate))
`

![Capture](https://user-images.githubusercontent.com/62568953/98447706-f2badc80-211e-11eb-8214-8c5940077d19.PNG)


Can you help please?
- Daz

**Comment by davet2001** [comment]
I don't think my script will do what you are looking for with your current hardware.

According to the image above the ener314-rt board has a serial interface so sadly you can't just toggle a line to turn the RF tx line on/off.

rpi-rf_send is for toggling one RPi gpio pin connected directly to a transmitter.

The engMQTTcient subscribes to mqtt topics that can be used to turn sockets on or off, and presumably sends and receives TRV data.

Since the TRVs need two way comms, I think you may need to stick with the ener314-rt.

I haven't used the ener314-rt directly with homeassistant and I don't know of any integrations, only via mqtt.

Usb DVB tv receiver is v helpful for debugging

Hopefully this helps!

**Comment by DrConradInTheHouse** [comment]
Many thanks for replying Dave and for sharing your expertise which is waaaay higher than my level.

Yes, this board is not the same as the "cheap 433RF" boards - although I wish it was. OOK and PSK doesnt help. I will just stick with the engMQTTclient then which does the job albeit a bit of an overkill - at least it works.

Thanks for the help

- daz
